
import static java.lang.Thread.sleep;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 393144069
 */
public class tela_inicial extends javax.swing.JFrame {

    public tela_inicial() {
        initComponents();

        new Thread() {
            public void run() {
                for (int i = 0; i <= 101; i++) {
                    try {
                        sleep(20);
                        carregamento.setValue(i);

                        if (carregamento.getValue() <= 30) {
                            mensagens.setText("Gerando perguntas");
                        } else if (carregamento.getValue() <= 60) {
                            mensagens.setText("Carregando as Perguntas");
                        } else if (carregamento.getValue() <= 90) {
                            mensagens.setText("Carregando o quiz");
                        } else {
                            mensagens.setText("Abertura do quiz concluida...");

                        }
                    } catch (InterruptedException ex) {
                    }
                }tela1 tl = new tela1();
                            tl.setVisible(true);
                            dispose();
            }
        }.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subtitulo = new javax.swing.JLabel();
        carregamento = new javax.swing.JProgressBar();
        mensagens = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        subtitulo.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        subtitulo.setForeground(new java.awt.Color(0, 0, 0));
        subtitulo.setText("TESTE SEUS CONHECIMENTOS");
        getContentPane().add(subtitulo);
        subtitulo.setBounds(40, 20, 720, 90);

        carregamento.setBackground(new java.awt.Color(7, 184, 0));
        carregamento.setStringPainted(true);
        getContentPane().add(carregamento);
        carregamento.setBounds(150, 470, 490, 30);

        mensagens.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(mensagens);
        mensagens.setBounds(300, 500, 350, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bk5.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JProgressBar carregamento;
    private javax.swing.JLabel mensagens;
    private javax.swing.JLabel subtitulo;
    // End of variables declaration//GEN-END:variables
}
