/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 393144069
 */
public class tela1 extends javax.swing.JFrame {

    /**
     * Creates new form tela1
     */
    public tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pergunta = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        Nvidas = new javax.swing.JLabel();
        Npontos = new javax.swing.JLabel();
        pontos = new javax.swing.JLabel();
        errada1 = new javax.swing.JRadioButton();
        certa = new javax.swing.JRadioButton();
        errada2 = new javax.swing.JRadioButton();
        errada3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        pergunta1 = new javax.swing.JLabel();
        pergunta2 = new javax.swing.JLabel();
        pergunta3 = new javax.swing.JLabel();
        pergunta4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        pergunta.setFont(new java.awt.Font("Elephant", 1, 22)); // NOI18N
        pergunta.setForeground(new java.awt.Color(255, 255, 255));
        pergunta.setText("01. Qual a montanha mais alta do Brasil?  ");
        getContentPane().add(pergunta);
        pergunta.setBounds(50, 190, 800, 50);

        titulo1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        titulo1.setText("VIDAS");
        getContentPane().add(titulo1);
        titulo1.setBounds(640, -10, 160, 90);

        Nvidas.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        Nvidas.setText("3");
        getContentPane().add(Nvidas);
        Nvidas.setBounds(700, 40, 40, 90);

        Npontos.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        Npontos.setText("0");
        getContentPane().add(Npontos);
        Npontos.setBounds(180, 20, 150, 30);

        pontos.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        pontos.setText("pontos:");
        getContentPane().add(pontos);
        pontos.setBounds(10, 20, 260, 30);

        errada1.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        errada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errada1ActionPerformed(evt);
            }
        });
        getContentPane().add(errada1);
        errada1.setBounds(90, 260, 20, 20);

        certa.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        certa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certaActionPerformed(evt);
            }
        });
        getContentPane().add(certa);
        certa.setBounds(90, 290, 20, 21);

        errada2.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        errada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errada2ActionPerformed(evt);
            }
        });
        getContentPane().add(errada2);
        errada2.setBounds(90, 320, 20, 20);

        errada3.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        errada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errada3ActionPerformed(evt);
            }
        });
        getContentPane().add(errada3);
        errada3.setBounds(90, 350, 20, 20);

        jButton1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jButton1.setText("Proxíma");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 450, 220, 50);

        pergunta1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        pergunta1.setForeground(new java.awt.Color(255, 255, 255));
        pergunta1.setText("A) Pico da Neblina");
        getContentPane().add(pergunta1);
        pergunta1.setBounds(110, 250, 310, 40);

        pergunta2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        pergunta2.setForeground(new java.awt.Color(255, 255, 255));
        pergunta2.setText("B) Pico Paraná");
        getContentPane().add(pergunta2);
        pergunta2.setBounds(110, 280, 310, 40);

        pergunta3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        pergunta3.setForeground(new java.awt.Color(255, 255, 255));
        pergunta3.setText("C) Monte Roraima");
        getContentPane().add(pergunta3);
        pergunta3.setBounds(110, 310, 310, 40);

        pergunta4.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        pergunta4.setForeground(new java.awt.Color(255, 255, 255));
        pergunta4.setText("D) Pico da Bandeira  ");
        getContentPane().add(pergunta4);
        pergunta4.setBounds(110, 340, 310, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bk4.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void errada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errada1ActionPerformed
       

    }//GEN-LAST:event_errada1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if (certa.isSelected()) {
            String pontos = "1";
            Npontos.setText(pontos);
            certa.setSelected(false);

            //questão 2
            pergunta.setText("02.Qual o nome do líder da Coreia do Norte?");
            pergunta1.setText("A) Pak Pong-ju");
            pergunta2.setText("B) Kim Jong-un");
            pergunta3.setText("C) Kim Jong-Il");
            pergunta4.setText("D)jack Chann moojin");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void errada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errada3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errada3ActionPerformed

    private void errada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errada2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errada2ActionPerformed

    private void certaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Npontos;
    private javax.swing.JLabel Nvidas;
    private javax.swing.JLabel background;
    private javax.swing.JRadioButton certa;
    private javax.swing.JRadioButton errada1;
    private javax.swing.JRadioButton errada2;
    private javax.swing.JRadioButton errada3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel pergunta;
    private javax.swing.JLabel pergunta1;
    private javax.swing.JLabel pergunta2;
    private javax.swing.JLabel pergunta3;
    private javax.swing.JLabel pergunta4;
    private javax.swing.JLabel pontos;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
